// Zweisprachige Texte (DE/EN). Verschachtelte Keys, via i18n.t('apps.chat') abrufbar.
export const dict = {
	de: {
		apps: { chat: 'Assistent', mail: 'Posteingang', docs: 'Dokumente', research: 'Recherche', studio: 'Studio', calendar: 'Kalender', agents: 'Team', tresor: 'Tresor', connections: 'Verbindungen', erweiterungen: 'Erweiterungen', settings: 'Einstellungen' },
		chat: { title: 'Assistent', eyebrow: 'Maschinenraum', newChat: 'Neuer Chat', placeholder: 'Nachricht an Astoris …', welcome: 'Womit fangen wir an?', welcomeSub: 'Dein Assistent läuft lokal und antwortet in Echtzeit.', history: 'Verlauf', noChats: 'Noch keine Gespräche.', persona: 'Persönlichkeit wählen' },
		settings: { title: 'Einstellungen', eyebrow: 'Astoris anpassen', appearance: 'Aussehen', accent: 'Akzentfarbe', fontSize: 'Schriftgröße', language: 'Sprache', model: 'KI-Modell', security: 'Sicherheit', logout: 'Abmelden', changePw: 'Passwort ändern', about: 'Über', compact: 'Kompakt', normal: 'Normal', large: 'Groß', mode: 'Modus', dark: 'Dunkel', light: 'Hell', notConnected: 'Nicht verbunden', connections: 'Verbindungen', signedInAs: 'Angemeldet als', viaTailscale: 'via Tailscale', viaPassword: 'via Passwort', currentPw: 'Aktuelles Passwort', newPw: 'Neues Passwort (min. 8 Zeichen)', changing: 'Ändere …', pwChanged: 'Passwort geändert.', pwTooShort: 'Neues Passwort: mindestens 8 Zeichen.', pwFailed: 'Fehlgeschlagen.', networkError: 'Netzwerkfehler.', aboutText: 'Astoris — dein eigener KI-Maschinenraum. Self-hosted, Open-Core.' },
		erweiterungen: { title: 'Erweiterungen', eyebrow: 'Add-ons', intro: 'Erweitere Astoris mit Add-ons. Lade Connector-Add-ons hoch — sicher, ohne Neustart.', upload: 'Add-on hochladen', installed: 'Installiert', none: 'Noch keine Add-ons installiert.', activate: 'Aktivieren', deactivate: 'Deaktivieren', remove: 'Entfernen', premium: 'Premium', free: 'Gratis', uploadHint: 'Connector-Add-on als .json (nur Daten, kein Code).', invalid: 'Ungültiges Add-on.', createCode: 'Code-Add-on erstellen', codeBadge: 'Code', edit: 'Code bearbeiten', editorTitle: 'Code-Add-on', nameLabel: 'Name', idLabel: 'ID (a-z, 0-9, -)', codeLabel: 'Code', testInput: 'Test-Eingabe (JSON, optional)', run: 'Testen', save: 'Speichern', output: 'Ergebnis', codeWarn: 'Code-Add-ons laufen mit Server-Rechten. Nur eigenen oder vertrauenswürdigen Code ausführen.', codePlaceholder: 'async function run(input) {\n  // dein Code – return das Ergebnis\n  return { ok: true };\n}', close: 'Schließen', saved: 'Gespeichert.' },
		common: { save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', connect: 'Verbinden', loading: 'Lädt …' },
		tresor: { title: 'Tresor', eyebrow: 'Ende-zu-Ende verschlüsselt', httpsBanner: 'Verschlüsselung braucht', httpsBannerSuffix: 'Öffne Astoris über', encrypt: 'Verschlüsseln', decrypt: 'Entschlüsseln', passphrase: 'Passphrase', passphraseHint: '(teile sie nur über einen sicheren Kanal)', passphrasePlaceholder: 'gemeinsames Geheimwort', message: 'Nachricht', plaintextPlaceholder: 'Klartext eingeben …', orFile: 'oder Datei', removeAttachment: 'Anhang entfernen', encryptedBlock: 'Verschlüsselter Block', encryptedBlockPlaceholder: '🛡️QR-ENC:… hier einfügen', working: 'Arbeite …', needPassphrase: 'Bitte eine Passphrase eingeben.', nothingToEncrypt: 'Nichts zu verschlüsseln.', failed: 'Fehlgeschlagen — falsche Passphrase oder beschädigter Block.', encryptedResult: 'Verschlüsselt — zum Versenden', decryptedResult: 'Entschlüsselt', copy: 'Kopieren', copied: '✓ kopiert', share: 'Teilen', shareNative: 'Teilen…', email: 'E-Mail', signalNote: 'In die Zwischenablage kopiert — in Signal einfügen (Signal bietet keinen Direkt-Link).', tooLongNote: 'Block zu groß für Direkt-Links — nutze „Teilen…" oder „Kopieren" und füge ihn manuell ein.', fileDecrypted: 'Datei entschlüsselt', saveFile: 'speichern', shareSubject: 'Verschlüsselte Nachricht (Astoris)' },
		connections: { title: 'Verbindungen', eyebrow: 'Was die KI bedienen darf', lead: 'Verbinde deine Alltags-Konten. Jede Verbindung wird beim Speichern live getestet, und die KI darf ausschließlich, was du je Verbindung erlaubst — sensible Aktionen sind standardmäßig aus.', connected: 'verbunden', active: 'aktiv', disconnect: 'Trennen', edit: 'Bearbeiten', connect: 'Verbinden', connectTitle: 'verbinden', optional: 'optional', permissions: 'Berechtigungen', sensitive: 'sensibel', test: 'Testen', testing: 'Teste …', connectSave: 'Verbinden & speichern', checking: 'Prüfe …', error: 'Fehler.', networkError: 'Netzwerkfehler.', credsNote: 'Zugangsdaten werden AES-256-verschlüsselt gespeichert · verlassen nie deinen Server' },
		mail: { title: 'Posteingang', eyebrow: 'E-Mail-Triage durch die KI', refresh: 'Aktualisieren', loadingMailbox: 'Postfach wird geladen …', noMailbox: 'Noch kein Postfach verbunden', noMailboxHint: 'Verbinde dein E-Mail-Konto unter Verbindungen, damit die KI deinen Posteingang lesen und zusammenfassen kann.', toConnections: 'Zu den Verbindungen', unreachable: 'Postfach nicht erreichbar', retry: 'Erneut versuchen', empty: 'Posteingang leer', emptyHint: 'Hier erscheinen deine neuesten Nachrichten.', messages: 'Nachrichten', unread: 'ungelesen', close: 'Schließen', from: 'Von', date: 'Datum', status: 'Status', read: 'Gelesen', unreadStatus: 'Ungelesen', bodyLoading: 'Nachrichtentext wird geladen …', bodyError: 'Nachrichtentext konnte nicht geladen werden.', noBody: 'Kein Nachrichtentext verfügbar.', mailboxFailed: 'Postfach konnte nicht geladen werden.' },
		docs: { title: 'Dokumente', eyebrow: 'Dein Wissensspeicher', uploading: 'Lade hoch …', dropHint: 'Datei hierher ziehen oder klicken', dropSub: 'PDF, Bilder, Texte und mehr — bis 25 MB pro Datei', searchPlaceholder: 'Dokumente durchsuchen …', clearSearch: 'Suche zurücksetzen', searching: 'Suche …', search: 'Suchen', hits: 'Treffer', notSearchable: 'nicht durchsuchbar', noHits: 'Keine Treffer für', skippedBinary: 'Übersprungen (binär):', loadingDocs: 'Lade Dokumente …', noDocs: 'Noch keine Dokumente', noDocsHint: 'Lade dein erstes Dokument hoch — es landet sicher in deinem lokalen Wissensspeicher.', uploadFirst: 'Erstes Dokument hochladen', document: 'Dokument', documents: 'Dokumente', aiSummary: 'KI-Zusammenfassung', summarizing: 'Wird zusammengefasst …', download: 'Herunterladen', deleteDoc: 'Dokument löschen?', deleteConfirm: 'wird unwiderruflich entfernt.', cancel: 'Abbrechen', delete: 'Löschen', loadFailed: 'Laden fehlgeschlagen', searchFailed: 'Suche fehlgeschlagen', summaryFailed: 'Zusammenfassung fehlgeschlagen', uploadFailed: 'Upload fehlgeschlagen', deleteFailed: 'Löschen fehlgeschlagen', unknownError: 'Unbekannter Fehler' },
		research: { title: 'Recherche', eyebrow: 'Web-Suche ohne Spuren', searchPlaceholder: 'Wonach möchtest du suchen?', searchLabel: 'Suchanfrage', searching: 'Suche…', search: 'Suchen', browsing: 'Durchsuche das Web…', networkError: 'Netzwerkfehler – Suche nicht möglich.', hitsFound: 'Treffer gefunden', emptyLead: 'Suche im Web – datensparsam über DuckDuckGo, ohne API-Schlüssel.', emptySub: 'Probier eine dieser Anfragen:' },
		studio: { title: 'Studio', eyebrow: 'Bild-Analyse', pickImage: 'Bitte eine Bilddatei wählen.', readFailed: 'Bild konnte nicht gelesen werden.', uploadImage: 'Bild hochladen', uploadHint: 'Klicken oder Datei hierher ziehen', preview: 'Vorschau', remove: 'Entfernen', promptLabel: 'Was möchtest du wissen?', promptOptional: '(optional)', promptPlaceholder: 'Beschreibe dieses Bild detailliert.', analyzing: 'Analysiere …', analyze: 'Analysieren', analysisFailed: 'Analyse fehlgeschlagen.', connectionFailed: 'Verbindung fehlgeschlagen.', description: 'Beschreibung' },
		calendar: { title: 'Kalender', eyebrow: 'Termine & Notizen', today: 'Heute', prevMonth: 'Vorheriger Monat', nextMonth: 'Nächster Monat', loading: 'Lädt …', noEventsDay: 'Keine Termine an diesem Tag.', deleteEvent: 'Termin löschen', titlePlaceholder: 'Titel', time: 'Uhrzeit', saving: 'Speichert …', add: 'Hinzufügen', notePlaceholder: 'Notiz (optional)', titleRequired: 'Titel ist erforderlich.', upcoming: 'Anstehend', noUpcoming: 'Keine anstehenden Termine.', loadFailed: 'Laden fehlgeschlagen', saveFailed: 'Speichern fehlgeschlagen', deleteFailed: 'Löschen fehlgeschlagen', unknownError: 'Unbekannter Fehler', weekdays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'], months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'] }
	},
	en: {
		apps: { chat: 'Assistant', mail: 'Inbox', docs: 'Documents', research: 'Research', studio: 'Studio', calendar: 'Calendar', agents: 'Team', tresor: 'Vault', connections: 'Connections', erweiterungen: 'Extensions', settings: 'Settings' },
		chat: { title: 'Assistant', eyebrow: 'Engine room', newChat: 'New chat', placeholder: 'Message Astoris …', welcome: 'Where shall we begin?', welcomeSub: 'Your assistant runs locally and replies in real time.', history: 'History', noChats: 'No conversations yet.', persona: 'Choose personality' },
		settings: { title: 'Settings', eyebrow: 'Customize Astoris', appearance: 'Appearance', accent: 'Accent color', fontSize: 'Font size', language: 'Language', model: 'AI model', security: 'Security', logout: 'Sign out', changePw: 'Change password', about: 'About', compact: 'Compact', normal: 'Normal', large: 'Large', mode: 'Mode', dark: 'Dark', light: 'Light', notConnected: 'Not connected', connections: 'Connections', signedInAs: 'Signed in as', viaTailscale: 'via Tailscale', viaPassword: 'via password', currentPw: 'Current password', newPw: 'New password (min. 8 characters)', changing: 'Changing …', pwChanged: 'Password changed.', pwTooShort: 'New password must be at least 8 characters.', pwFailed: 'Failed.', networkError: 'Network error.', aboutText: 'Astoris — your own AI engine room. Self-hosted, open-core.' },
		erweiterungen: { title: 'Extensions', eyebrow: 'Add-ons', intro: 'Extend Astoris with add-ons. Upload connector add-ons — safely, no restart.', upload: 'Upload add-on', installed: 'Installed', none: 'No add-ons installed yet.', activate: 'Activate', deactivate: 'Deactivate', remove: 'Remove', premium: 'Premium', free: 'Free', uploadHint: 'Connector add-on as .json (data only, no code).', invalid: 'Invalid add-on.', createCode: 'Create code add-on', codeBadge: 'Code', edit: 'Edit code', editorTitle: 'Code add-on', nameLabel: 'Name', idLabel: 'ID (a-z, 0-9, -)', codeLabel: 'Code', testInput: 'Test input (JSON, optional)', run: 'Test', save: 'Save', output: 'Result', codeWarn: 'Code add-ons run with server privileges. Only run your own or trusted code.', codePlaceholder: 'async function run(input) {\n  // your code – return the result\n  return { ok: true };\n}', close: 'Close', saved: 'Saved.' },
		common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', connect: 'Connect', loading: 'Loading …' },
		tresor: { title: 'Vault', eyebrow: 'End-to-end encrypted', httpsBanner: 'Encryption requires', httpsBannerSuffix: 'Open Astoris over', encrypt: 'Encrypt', decrypt: 'Decrypt', passphrase: 'Passphrase', passphraseHint: '(share it only over a secure channel)', passphrasePlaceholder: 'shared secret word', message: 'Message', plaintextPlaceholder: 'Enter plain text …', orFile: 'or file', removeAttachment: 'Remove attachment', encryptedBlock: 'Encrypted block', encryptedBlockPlaceholder: 'Paste 🛡️QR-ENC:… here', working: 'Working …', needPassphrase: 'Please enter a passphrase.', nothingToEncrypt: 'Nothing to encrypt.', failed: 'Failed — wrong passphrase or corrupted block.', encryptedResult: 'Encrypted — ready to send', decryptedResult: 'Decrypted', copy: 'Copy', copied: '✓ copied', share: 'Share', shareNative: 'Share…', email: 'Email', signalNote: 'Copied to clipboard — paste it into Signal (Signal offers no direct link).', tooLongNote: 'Block too large for direct links — use “Share…” or “Copy” and paste it manually.', fileDecrypted: 'File decrypted', saveFile: 'Save', shareSubject: 'Encrypted message (Astoris)' },
		connections: { title: 'Connections', eyebrow: 'What the AI is allowed to do', lead: 'Connect your everyday accounts. Every connection is tested live when you save it, and the AI may only do what you allow per connection — sensitive actions are off by default.', connected: 'connected', active: 'active', disconnect: 'Disconnect', edit: 'Edit', connect: 'Connect', connectTitle: 'connect', optional: 'optional', permissions: 'Permissions', sensitive: 'sensitive', test: 'Test', testing: 'Testing …', connectSave: 'Connect & save', checking: 'Checking …', error: 'Error.', networkError: 'Network error.', credsNote: 'Credentials are stored AES-256 encrypted · they never leave your server' },
		mail: { title: 'Inbox', eyebrow: 'AI-powered email triage', refresh: 'Refresh', loadingMailbox: 'Loading mailbox …', noMailbox: 'No mailbox connected yet', noMailboxHint: 'Connect your email account under Connections so the AI can read and summarize your inbox.', toConnections: 'Go to Connections', unreachable: 'Mailbox unreachable', retry: 'Try again', empty: 'Inbox empty', emptyHint: 'Your latest messages will appear here.', messages: 'messages', unread: 'unread', close: 'Close', from: 'From', date: 'Date', status: 'Status', read: 'Read', unreadStatus: 'Unread', bodyLoading: 'Loading message body …', bodyError: 'The message body could not be loaded.', noBody: 'No message body available.', mailboxFailed: 'The mailbox could not be loaded.' },
		docs: { title: 'Documents', eyebrow: 'Your knowledge store', uploading: 'Uploading …', dropHint: 'Drag a file here or click', dropSub: 'PDFs, images, text and more — up to 25 MB per file', searchPlaceholder: 'Search documents …', clearSearch: 'Clear search', searching: 'Searching …', search: 'Search', hits: 'hits', notSearchable: 'not searchable', noHits: 'No results for', skippedBinary: 'Skipped (binary):', loadingDocs: 'Loading documents …', noDocs: 'No documents yet', noDocsHint: 'Upload your first document — it lands safely in your local knowledge store.', uploadFirst: 'Upload first document', document: 'document', documents: 'documents', aiSummary: 'AI summary', summarizing: 'Summarizing …', download: 'Download', deleteDoc: 'Delete document?', deleteConfirm: 'will be removed permanently.', cancel: 'Cancel', delete: 'Delete', loadFailed: 'Loading failed', searchFailed: 'Search failed', summaryFailed: 'Summary failed', uploadFailed: 'Upload failed', deleteFailed: 'Deletion failed', unknownError: 'Unknown error' },
		research: { title: 'Research', eyebrow: 'Web search without a trace', searchPlaceholder: 'What would you like to search for?', searchLabel: 'Search query', searching: 'Searching…', search: 'Search', browsing: 'Searching the web…', networkError: 'Network error – search not possible.', hitsFound: 'results found', emptyLead: 'Search the web – privacy-friendly via DuckDuckGo, no API key.', emptySub: 'Try one of these queries:' },
		studio: { title: 'Studio', eyebrow: 'Image analysis', pickImage: 'Please choose an image file.', readFailed: 'The image could not be read.', uploadImage: 'Upload image', uploadHint: 'Click or drag a file here', preview: 'Preview', remove: 'Remove', promptLabel: 'What would you like to know?', promptOptional: '(optional)', promptPlaceholder: 'Describe this image in detail.', analyzing: 'Analyzing …', analyze: 'Analyze', analysisFailed: 'Analysis failed.', connectionFailed: 'Connection failed.', description: 'Description' },
		calendar: { title: 'Calendar', eyebrow: 'Events & notes', today: 'Today', prevMonth: 'Previous month', nextMonth: 'Next month', loading: 'Loading …', noEventsDay: 'No events on this day.', deleteEvent: 'Delete event', titlePlaceholder: 'Title', time: 'Time', saving: 'Saving …', add: 'Add', notePlaceholder: 'Note (optional)', titleRequired: 'Title is required.', upcoming: 'Upcoming', noUpcoming: 'No upcoming events.', loadFailed: 'Loading failed', saveFailed: 'Saving failed', deleteFailed: 'Deletion failed', unknownError: 'Unknown error', weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] }
	}
} as const;

export type Lang = keyof typeof dict;
